### PR TITLE
Auth failfast

### PR DESCRIPTION
**Pull request by devrandom**
Don't try to read a body on a 401 response since `bitcoind` doesn't send one.  Attempting to read a body results in an uninformative timeout error.

~~Also updates creat name to match what was actually released.~~

### CODE REVIEW

**Comment by devrandom** [comment]
ping @JeremyRubin

**Comment by JeremyRubin** [comment]
thank you! for whatever reason my gh notifs are messed up and i never see anything unless tagged explicitly.

**Comment by JeremyRubin** [comment]
why are you renaming the crate in this PR?

**Comment by JeremyRubin** [comment]
i'll need to push the actualy commit / version bump here, plz drop that commit.

**Comment by devrandom** [comment]
Sounds good, commit dropped.

**Comment by JeremyRubin** [comment]
thank you 🙏 

will do a release with this shortly.

**Comment by JeremyRubin** [comment]
btw did you want to upstream this to the non asyncversiion?

**Comment by devrandom** [comment]
> btw did you want to upstream this to the non asyncversiion?

will do

**Pull request merged**
